version: '3.8'
services:
  mumble:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
    ports:
      - "${PORTS}:${PORTS}/tcp"
      - "${PORTS}:${PORTS}/udp"
    volumes:
      - ${CONFIG_PATH}:/data/config.ini