version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SUPERUSER_PASSWORD: /run/secrets/superuser_password
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    secrets:
      - superuser_password
secrets:
  superuser_password:
    file: ./secrets/password.txt